services:
  bot:
    build:
      context: .
      target: dev
    image: ghcr.io/pauk-slon/immer-wiederholen:dev
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_FSM_STORAGE_URL: redis://valkey:6379/1
      STUDENT_RECORD_STORAGE_URL: redis://valkey:6379/0
    volumes:
      - .:/app
    depends_on:
      - valkey

  reminder:
    image: ghcr.io/pauk-slon/immer-wiederholen:dev
    restart: unless-stopped
    command: python -m wiederholen.bot.reminder
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_FSM_STORAGE_URL: redis://valkey:6379/1
      STUDENT_RECORD_STORAGE_URL: redis://valkey:6379/0
    volumes:
      - .:/app
    depends_on:
      - valkey

  valkey:
    image: valkey/valkey:8-alpine
    restart: unless-stopped
    volumes:
      - ./.local/valkey/data:/data
